/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminShtoRouteImport } from './routes/admin.shto'
import { Route as AdminPorositeRouteImport } from './routes/admin.porosite'
import { Route as AdminImportoRouteImport } from './routes/admin.importo'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShtoRoute = AdminShtoRouteImport.update({
  id: '/shto',
  path: '/shto',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPorositeRoute = AdminPorositeRouteImport.update({
  id: '/porosite',
  path: '/porosite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportoRoute = AdminImportoRouteImport.update({
  id: '/importo',
  path: '/importo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/importo': typeof AdminImportoRoute
  '/admin/porosite': typeof AdminPorositeRoute
  '/admin/shto': typeof AdminShtoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/importo': typeof AdminImportoRoute
  '/admin/porosite': typeof AdminPorositeRoute
  '/admin/shto': typeof AdminShtoRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/importo': typeof AdminImportoRoute
  '/admin/porosite': typeof AdminPorositeRoute
  '/admin/shto': typeof AdminShtoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/importo'
    | '/admin/porosite'
    | '/admin/shto'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/importo' | '/admin/porosite' | '/admin/shto' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/importo'
    | '/admin/porosite'
    | '/admin/shto'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shto': {
      id: '/admin/shto'
      path: '/shto'
      fullPath: '/admin/shto'
      preLoaderRoute: typeof AdminShtoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/porosite': {
      id: '/admin/porosite'
      path: '/porosite'
      fullPath: '/admin/porosite'
      preLoaderRoute: typeof AdminPorositeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importo': {
      id: '/admin/importo'
      path: '/importo'
      fullPath: '/admin/importo'
      preLoaderRoute: typeof AdminImportoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminImportoRoute: typeof AdminImportoRoute
  AdminPorositeRoute: typeof AdminPorositeRoute
  AdminShtoRoute: typeof AdminShtoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportoRoute: AdminImportoRoute,
  AdminPorositeRoute: AdminPorositeRoute,
  AdminShtoRoute: AdminShtoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
